config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  get 'restaurants/about' => 'restaurants#about'
  get 'restaurants/:restaurant_id/bookmarks' => 'bookmarks#create'
  get 'restaurants/:restaurant_id/bookmarks/:id' => 'bookmarks#destroy'
  get 'restaurants/:restaurant_id/comments/:id' => 'comments#destroy'
  resources :restaurants do
    resources :bookmarks, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  root 'restaurants#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def remember_me
    true
  end
  
  has_many :restaurants, dependent: :destroy 
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_restaurants, through: :bookmarks, source: :restaurant
  has_many :comments, dependent: :destroy
  has_many :commented_restaurants, through: :comments, source: :restaurant
  validates :name, presence: true

  def already_bookmarked?(restaurant)
    self.bookmarks.exists?(restaurant_id: restaurant.id)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def after_sign_up_path_for(resource)
    if current_user.status == "true"
      user_path(resource)
    else
      session[:previous_url] || root_path
    end
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    if current_user.status == "true"
      user_path(resource)
    else
      session[:previous_url] || root_path
    end
  end

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= stylesheet_link_tag 'mypage', :media => "all" %>
<% if current_user.status == "true" %>
<div class="mypagecontent">
<h1 style="display:inline" class="mypagetitle"><%= @user.name %>様の管理ページ</h1>

<% if current_user.id == @user.id %>
  <%= link_to "ユーザー情報編集", edit_user_registration_path %><br>
<% end %>

<div class="owningtitle">
<h2>登録済み店舗(<%= @user.restaurants.count %>件)</h2>
<%= button_to "新規店舗登録", new_restaurant_path, method: :get, class: "newrestaurantbutton" %>
</div>
<% @user.restaurants.each do |t| %>
  <ul class="mypagelistu">
  <li class="mypagelisti">
    <%= image_tag t.image_url, size: "150x120" if t.image? %>
    <div class="owningtexts">
      <p class="owningname"><%= link_to t.name, restaurant_path(t.id) %></p>
      <div class="owningfunction">
        <%= link_to "編集", edit_restaurant_path(t.id) %>
        <%= button_to "削除", restaurant_path(t.id), method: :delete, class:"restaurantdelete" %>
      </div>
    </div>
  </li>
  </ul>
<% end %>

<%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logoutbottun" %>

<%= link_to "トップページに戻る", restaurants_path, style: "margin-left: 30px;" %>
</div>
<% else %>
<div class="mypagecontent">
<h1 style="display:inline" class="mypagetitle"><%= @user.name %>さんのマイページ</h1>

<% if current_user.id == @user.id %>
  <%= link_to "ユーザー情報編集", edit_user_registration_path %>
<% end %>

<h2 style="margin-left: 30px;" >投稿済みコメント一覧(<%= @user.commented_restaurants.count %>件)</h2>
<% @user.commented_restaurants.each do |restaurant| %>
  <ul class="commentlistu">
  <li class="commentlisti">
    <% restaurant.comments.where(user_id: current_user.id).each do |comment| %>
      <div class="commentdetails">
      <%= image_tag comment.image_url, size: "150x120" if comment.image? %>
      <div class="commenttexts">
      <div>
      <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %><br>
    「<%= comment.content %>」
    (<%= link_to restaurant.name, restaurant_path(restaurant.id) %>)&nbsp;
    <% if current_user.already_bookmarked?(restaurant) %>
        <%= link_to restaurant_bookmark_path(id: restaurant.id, restaurant_id: restaurant.id), method: :delete do %>
            <i class="fa-solid fa-star" style="color:#FAE013;"></i>
        <% end %>
    <% else %>
        <%= link_to restaurant_bookmarks_path(id: restaurant.id, restaurant_id: restaurant.id), method: :post do %>
            <i class="fa-solid fa-star" style="color:#cecece;"></i>
        <% end %>
    <% end %></div>
    <%= link_to "このコメントを削除", restaurant_comment_path(restaurant.id, comment.id), method: :delete, data: {confirm: "本当に削除しますか？" }, class: "commentdelete" %>
    <% end %>
    </div>
    </div>
    </li>
  </ul>
<% end %>

<h2 style="margin-left: 30px;" >ブックマーク済み店舗一覧(<%= @user.bookmarked_restaurants.count %>件)</h2>
<% @user.bookmarked_restaurants.each do |restaurant| %>
  <ul class="mypagelistu">
  <li class="mypagelisti">
  <%= image_tag restaurant.image_url, size: "150x120" if restaurant.image? %>
  <div class="texts">
  <%= link_to restaurant.name, restaurant_path(restaurant.id),class: "restaurantname" %>
  <% if current_user.already_bookmarked?(restaurant) %>
    <%= link_to restaurant_bookmark_path(id: restaurant.id, restaurant_id: restaurant.id), method: :delete do %>
      <i class="fa-solid fa-star size" style="color:#FAE013"></i>
    <% end %>
  <% end %><br>
  <%= restaurant.about %>
  <div class="restauranttaglist">
  <% restaurant.tags.each do |tag| %>
    <span class="restauranttag">#<%= tag.name %></span>
  <% end %>
  </div>
  </div>
  </li>
  </ul>
<% end %>


<%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logoutbottun" %>

<%= link_to "トップページに戻る", restaurants_path, style: "margin-left: 30px;" %>
</div>
<% end %>