config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  get 'restaurants/about' => 'restaurants#about'
  get 'restaurants/:restaurant_id/bookmarks' => 'bookmarks#create'
  get 'restaurants/:restaurant_id/bookmarks/:id' => 'bookmarks#destroy'
  get 'restaurants/:restaurant_id/comments/:id' => 'comments#destroy'
  resources :restaurants do
    resources :bookmarks, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  root 'restaurants#index'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, if: :address_changed?
    mount_uploader :image, ImageUploader
    belongs_to :user
    def self.ransackable_attributes(auth_object = nil)
        ["about", "genre", "name"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["user"]
    end

    validates :name, presence: true
    validates :addresscode, presence: true
    validates :address, presence: true
    validates :opentime, presence: true
    validates :endtime, presence: true

    has_many :restaurant_tag_relations, dependent: :destroy
    has_many :tags, through: :restaurant_tag_relations, dependent: :destroy
    has_many :bookmarks, dependent: :destroy
    has_many :bookmarked_users, through: :bookmarks, source: :user
    has_many :comments, dependent: :destroy
    has_many :commented_users, through: :comments, source: :user
    ransack_alias :tag, :tags_name
    has_many_attached :menufile

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_q, only: [:index, :search]

    def index
      @forkeyvisual = Restaurant.order("RANDOM()").all
      @restaurant = Restaurant.all
      @tag = Tag.all
    end

    def about

    end

    def new
        @restaurant = Restaurant.new
    end
    
      def create
        restaurant = Restaurant.new(restaurant_params)
        restaurant.user_id = current_user.id
        if restaurant.save!
          redirect_to :action => "show", :id => restaurant.id
        else
          redirect_to :action => "new"
        end
      end

      def show
        @restaurant = Restaurant.find(params[:id])
        @comments = @restaurant.comments
        @comment = Comment.new
      end

      def edit
        @restaurant = Restaurant.find(params[:id])
      end

      def update
        restaurant = Restaurant.find(params[:id])
        if restaurant.update(restaurant_params)
          redirect_to :action => "show", :id => restaurant.id
        else
          redirect_to :action => "new"
        end
      end
    
      def destroy
        restaurant = Restaurant.find(params[:id])
        restaurant.destroy
        redirect_to action: :index
      end

      def search
        day = Date.today.wday
        puts day
        @results = @q.result(distinct: true)
        @restaurant_tags = {}
        @results.each do |restaurant|
          @restaurant_tags[restaurant.id] = restaurant.tags
        end
        if params[:q][:tag_ids_in].present?
          @results = @results.joins(:tags).where(tags: { id: params[:q][:tag_ids_in] })
          @results = @results.group('restaurants.id').having('COUNT(tags.id) = ?', params[:q][:tag_ids_in].size)
        end
        if params[:latitude].present? && params[:longitude].present?
          latitude = params[:latitude].to_f
          longitude = params[:longitude].to_f
    
          @results = @results.near([latitude, longitude], 10)
        end

        if day == 0
          @results=@results.where(dayoffsun: false)
        elsif day == 1
          @results=@results.where(dayoffmon: false)
        elsif day == 2
          @results=@results.where(dayofftue: false)
        elsif day == 3
          @results=@results.where(dayoffwed: false)
        elsif day == 4
          @results=@results.where(dayoffthu: false)
        elsif day == 5
          @results=@results.where(dayofffri: false)
        else
          @results=@results.where(dayoffsat: false)
        end

        @current_time = Time.current.to_s(:time)

        @restaurant = Restaurant.all
        @tag = Tag.all
      end
                                          
      private

      def set_q
        if params[:q].present?    
          if params[:q][:name_or_about_or_genre_cont_all].present?
            params[:q][:name_or_about_or_genre_cont_all] = params[:q][:name_or_about_or_genre_cont_all].split(/[\p{blank}\s]+/)
          end
          @q = Restaurant.includes(:tags).ransack(params[:q])
        else
          @q = Restaurant.ransack(params[:q])
        end
      end  
                                                                                                                                                          
      def restaurant_params
        params.require(:restaurant).permit(:name, :genre, :address, :mapurl, :addresscode, :about, :image, :opentime, :endtime, :phone, :website, :whatsnew, :pay, :seattype, :dayoffmon, :dayofftue, :dayoffwed, :dayoffthu, :dayofffri, :dayoffsat, :dayoffsun, :latitude, :longitude, tag_ids: [], content: [])
      end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
    def dayoff_columns
        ['dayoffmon', 'dayofftue', 'dayoffwed', 'dayoffthu', 'dayofffri', 'dayoffsat', 'dayoffsun']
    end
end

app/views/restaurants/about.html.erb
<%= stylesheet_link_tag 'about', :media => "all" %>
<div class="about">
<div class="abouttitle">
<h1 style="display:inline">About&ensp;</h1><%= image_tag "toukalogo.png", style: "height:60px;margin-bottom:8px;"%>
</div>
<div class="aboutcontent1">
<div class="abouttext1">
<h3 class="texttitle">外ご飯選び。困ったこと、ありませんか？</h3>
<p>外出先でお店を探そうと思っても、<br>なかなか思うようなお店が見つからない……。<br>
    探すのも面倒でいつも同じようなお店やチェーン店に入ってしまう……。<br>
    一人だと、なかなかお店を開拓しづらい……。<br>
    日頃、このように感じることはありませんか？<br>
    <span class="marker">「さくめし」はそんなあなたにぴったりの飲食店サーチサイトです！</span></p>
</div>
<%= image_tag "aboutimage1.jpg", class: "aboutimage1" %>
</div>

<h3 class="texttitle" style="font-size:30px">"さくめし"の特徴</h3>
<div class="aboutcontent2">
<div class="feature1"><strong style="font-size:17px;display:block">①「いま食べたい」にサクッと出会える！</strong><br>
    フリーワードと、豊富なタグから飲食店を絞り込んで検索できます！<br>
    タグを複数選択すれば、その分ぴったりの飲食店が絞り込めます♪</div>
<div class="feature2"><strong style="font-size:17px;display:block">②出会ったら、サクッと食べに行こう！</strong><br>
    検索結果が近い順に表示され、かつマップにすぐ飛べるようになっています！<br>
    絞り込み→お店にすぐGO!!が可能です♪</div>
<div class="feature3"><strong style="font-size:17px;display:block">③コメント＆ブックマークを活用しよう！</strong><br>
    コメントでみんなの感想を見てみよう！食べにいったらあなたもサクッとコメント♪<br>
    気に入ったら・気になったら☆ボタンでブックマーク！</div>
</div>


<span style="color:orange;font-size:20px">▷<%= link_to "トップページに戻ってさっそくお店を探そう！",restaurants_path ,class: "toplink" %>◁</span>
</div>

app/views/restaurants/search.html.erb
<%= stylesheet_link_tag 'search', :media => "all" %>

<h1 class="searchtitle">検索結果</h1>
<% unless user_signed_in? %>
<p class="indicate"><i class="fa-solid fa-circle-exclamation" style="color:orange;"></i> ブックマーク・コメント機能を使うには<b><%= link_to "ログイン", new_user_session_path %></b>してください。</p>
<% end %>
<div class="searchresult">
<% @results.each do |restaurant| %>
<% if restaurant.opentime.to_s(:time) <= @current_time && restaurant.endtime.to_s(:time) >= @current_time %>
  <ul class="restaurantlistu">
  <li class="restaurantlisti">
    <%= image_tag restaurant.image_url, size: "150x120" if restaurant.image? %>
    <div class="texts">
    <%= link_to restaurant.name, restaurant_path(restaurant.id), class: "restaurantname" %>
    <% if user_signed_in? && current_user.status == "false" %>
    <% if current_user.already_bookmarked?(restaurant) %>
        <%= link_to restaurant_bookmark_path(id: restaurant.id, restaurant_id: restaurant.id), method: :delete do %>
            <i class="fa-solid fa-star size" style="color:#FAE013;"></i>
        <% end %>
    <% else %>
        <%= link_to restaurant_bookmarks_path(id: restaurant.id, restaurant_id: restaurant.id), method: :post do %>
            <i class="fa-solid fa-star size" style="color:#cecece;"></i>
        <% end %>
    <% end %>
  <% end %><br>
  <%= restaurant.about %>
  <div class="restauranttaglist">
  <% @restaurant_tags[restaurant.id].each do |tag| %>
    <span class="restauranttag">#<%= tag.name %></span>
  <% end %>
  </div>
  </div>
</li>
  </ul>
<% end %>
<% end %>
</div>

<h3>検索条件変更</h3>
<%= search_form_for @q, url: search_restaurants_path, id: "searchForm", class:'searchfield' do |f| %>
<div class="freeword">
  <%= f.label :name_or_about_or_genre_cont_all, "フリーワードで検索　" %>
  <%= f.search_field :name_or_about_or_genre_cont_all , :size => 110, style: "border: 1.5px solid #2c2c2c; border-radius: 3px;margin-left:10px" %>
</div>
  <br>
  <div class="tag">
  <%= f.label :tag_ids, "　　　 タグで検索 　", class: "taglabel" %>
  <div class="tagcontent">
  <p class="taggenre">お店の特徴</p>
  <ul class="taglistu" style="background-color:#FFEBEB;border-radius:5px">
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 1, params.dig(:q, :tag_ids_in)&.include?(1) %>
        #<%= @tag[0]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 2, params.dig(:q, :tag_ids_in)&.include?(2) %>
        #<%= @tag[1]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 3, params.dig(:q, :tag_ids_in)&.include?(3) %>
        #<%= @tag[2]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 16, params.dig(:q, :tag_ids_in)&.include?(16) %>
        #<%= @tag[15]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 20, params.dig(:q, :tag_ids_in)&.include?(20) %>
        #<%= @tag[19]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 21, params.dig(:q, :tag_ids_in)&.include?(21) %>
        #<%= @tag[20]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 41, params.dig(:q, :tag_ids_in)&.include?(41) %>
        #<%= @tag[40]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 43, params.dig(:q, :tag_ids_in)&.include?(43) %>
        #<%= @tag[42]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 42, params.dig(:q, :tag_ids_in)&.include?(42) %>
        #<%= @tag[41]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 39, params.dig(:q, :tag_ids_in)&.include?(39) %>
        #<%= @tag[38]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 40, params.dig(:q, :tag_ids_in)&.include?(40) %>
        #<%= @tag[39]['name'] %>
        </li>
    </ul>
    <p class="taggenre">シーン</p>
    <ul class="taglistu" style="background-color:#E5FEFF;border-radius:5px">
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 4, params.dig(:q, :tag_ids_in)&.include?(4) %>
        #<%= @tag[3]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 5, params.dig(:q, :tag_ids_in)&.include?(5) %>
        #<%= @tag[4]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 6, params.dig(:q, :tag_ids_in)&.include?(6) %>
        #<%= @tag[5]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 7, params.dig(:q, :tag_ids_in)&.include?(7) %>
        #<%= @tag[6]['name'] %>
        </li>
    </ul>
    <p class="taggenre">気分</p>
    <ul class="taglistu" style="background-color:#FFFEC0;border-radius:5px">
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 8, params.dig(:q, :tag_ids_in)&.include?(8) %>
        #<%= @tag[7]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 9, params.dig(:q, :tag_ids_in)&.include?(9) %>
        #<%= @tag[8]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 10, params.dig(:q, :tag_ids_in)&.include?(10) %>
        #<%= @tag[9]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 11, params.dig(:q, :tag_ids_in)&.include?(11) %>
        #<%= @tag[10]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 12, params.dig(:q, :tag_ids_in)&.include?(12) %>
        #<%= @tag[11]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 13, params.dig(:q, :tag_ids_in)&.include?(13) %>
        #<%= @tag[12]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 15, params.dig(:q, :tag_ids_in)&.include?(15) %>
        #<%= @tag[14]['name'] %>
        </li>
    </ul>
    <p class="taggenre">価格帯</p>
    <ul class="taglistu" style="background-color:#E4FFE9;border-radius:5px">
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 17, params.dig(:q, :tag_ids_in)&.include?(17) %>
        #<%= @tag[16]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 18, params.dig(:q, :tag_ids_in)&.include?(18) %>
        #<%= @tag[17]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 19, params.dig(:q, :tag_ids_in)&.include?(19) %>
        #<%= @tag[18]['name'] %>
        </li>
    </ul>
    <p class="taggenre">ジャンル</p>
    <ul class="taglistu" style="background-color:#E7E4FF;border-radius:5px">
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 22, params.dig(:q, :tag_ids_in)&.include?(22) %>
        #<%= @tag[21]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 23, params.dig(:q, :tag_ids_in)&.include?(23) %>
        #<%= @tag[22]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 24, params.dig(:q, :tag_ids_in)&.include?(24) %>
        #<%= @tag[23]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 25, params.dig(:q, :tag_ids_in)&.include?(25) %>
        #<%= @tag[24]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 26, params.dig(:q, :tag_ids_in)&.include?(26) %>
        #<%= @tag[25]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 27, params.dig(:q, :tag_ids_in)&.include?(27) %>
        #<%= @tag[26]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 28, params.dig(:q, :tag_ids_in)&.include?(28) %>
        #<%= @tag[27]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 29, params.dig(:q, :tag_ids_in)&.include?(29) %>
        #<%= @tag[28]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 30, params.dig(:q, :tag_ids_in)&.include?(30) %>
        #<%= @tag[29]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 31, params.dig(:q, :tag_ids_in)&.include?(31) %>
        #<%= @tag[30]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 32, params.dig(:q, :tag_ids_in)&.include?(32) %>
        #<%= @tag[31]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 33, params.dig(:q, :tag_ids_in)&.include?(33) %>
        #<%= @tag[32]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 34, params.dig(:q, :tag_ids_in)&.include?(34) %>
        #<%= @tag[33]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 35, params.dig(:q, :tag_ids_in)&.include?(35) %>
        #<%= @tag[34]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 36, params.dig(:q, :tag_ids_in)&.include?(36) %>
        #<%= @tag[35]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 37, params.dig(:q, :tag_ids_in)&.include?(37) %>
        #<%= @tag[36]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 38, params.dig(:q, :tag_ids_in)&.include?(38) %>
        #<%= @tag[37]['name'] %>
        </li>
        <li class="taglisti">
        <%= check_box_tag "q[tag_ids_in][]", 14, params.dig(:q, :tag_ids_in)&.include?(14) %>
        #<%= @tag[13]['name'] %>
        </li>
    </ul>
    </div>
  </div>
  <%= hidden_field_tag :'latitude', id: "latitude" %>
  <%= hidden_field_tag :'longitude', id: "longitude" %>

  <%= button_tag type: "button", onclick: "getLocation()", id: "searchButton" do %>
  <i class="fa-solid fa-magnifying-glass"></i>&ensp;検索する！
  <% end %>
<% end %>


<script>

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else { 
        alert("Geolocation is not supported by this browser.");
    }
}

function showPosition(position) {
    $.ajax({
        type: 'GET',
        url: `https://maps.googleapis.com/maps/api/geocode/json?latlng=${position.coords.latitude},${position.coords.longitude}&sensor=true&key=<%= ENV['MAP_API_KEY'] %>&language=en`,
    }).then(function(response){
        var lat = Number(response.results[0].geometry.location.lat);
        var lng = Number(response.results[0].geometry.location.lng);

        // フォームに位置情報を反映させる
        document.getElementById('latitude').value = lat;
        document.getElementById('longitude').value = lng;

        // フォームをサブミットする
        document.getElementById('searchForm').submit();
    });
}
</script>

    document.getElementById('clearCanvas').addEventListener('click', function() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      // Optionally, you can also save the cleared state to the database
      document.getElementById('canvas_data').value = '';
      document.getElementById('canvasForm').submit();
    });

app/views/restaurants/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<div class="restaurantinfo">
<h1 style="font-size:45px"><%= @restaurant.name %>
    <% if user_signed_in? %>
      <% if current_user.status == "false" %>
        <% if current_user.already_bookmarked?(@restaurant) %>
          <%= link_to restaurant_bookmark_path(@restaurant), method: :delete do %>
            <i class="fa-solid fa-star fa-xs" style="color:#FAE013;"></i>
          <% end %>
        <% else %>
          <%= link_to restaurant_bookmarks_path(@restaurant), method: :post do %>
            <i class="fa-solid fa-star fa-xs" style="color:#cecece;"></i>
          <% end %>
        <% end %>
      <% end %>
    <% end %></h1>
<p class="abouttext"><%= @restaurant.about %></p>
<% @restaurant.tags.each do |tag| %>
    <span class="restauranttag">#<%= tag.name %></span>
<% end %>
    <% unless user_signed_in? %>
      <br><p class="indicate"><i class="fa-solid fa-circle-exclamation" style="color:orange;"></i> ブックマーク・コメント機能を使うには<b><%= link_to "ログイン", new_user_session_path %></b>してください。</p>
    <% end %><br>

<%= image_tag @restaurant.image_url, height: 300, 
    class: "mainimage", style: "object-fit: contain;" if @restaurant.image? %>
<div class="detail">
  <div class="basic">
  <p class="detailstitle">店舗基本情報</p>
  <table class="basictable">
  <tr><td align="center" width="102" style="background-color: rgb(239, 239, 239)">ジャンル</td><td style="background-color: rgb(239, 239, 239)"><%= @restaurant.genre %></td></tr>
  <tr><td align="center" rowspan=2 style="background-color: rgb(249, 249, 249)">住所</td><td style="border-bottom-style:hidden;padding-bottom:0px;background-color: rgb(249, 249, 249)">〒<%= @restaurant.addresscode %></td></tr>
  <tr><td style="padding-top:0px;background-color: rgb(249, 249, 249)"><%= @restaurant.address %></td></tr>
  <tr><td align="center" rowspan=2 style="background-color: rgb(239, 239, 239)">Map</td><td style="border-bottom-style:hidden;padding-bottom:0px;background-color: rgb(239, 239, 239);"><%= link_to @restaurant.mapurl, @restaurant.mapurl %></td></tr>

  <tr><td style="background-color: rgb(239, 239, 239)"><div id="map" style="height: 270px; width: 360px;"></div>

  <script type="text/javascript">
    function initMap() {
      var test ={lat: <%= @restaurant.latitude %>, lng: <%= @restaurant.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

      var contentString = '住所：<%= @restaurant.address %>';
      var infowindow = new google.maps.InfoWindow({
        content: contentString
      });

      var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                  });

      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAP_API_KEY'] %>&libraries=places&callback=initMap" async defer></script></td></tr>

  <tr><td align="center" style="background-color: rgb(249, 249, 249)">営業時間</td><td style="background-color: rgb(249, 249, 249)"><%= l @restaurant.opentime %>～<%= l @restaurant.endtime %></td><tr>
  <tr><td align="center" style="background-color: rgb(239, 239, 239)">定休日</td><td style="background-color: rgb(239, 239, 239)">
  <%  dayoff_columns.each_with_index do |day,i| %>
    <% if @restaurant[day] == true %>
      <a><%= ["月曜日","火曜日","水曜日","木曜日","金曜日","土曜日","日曜日"][i] %></a>
    <% end %>
  <% end %></td></tr>
  <tr><td align="center" style="background-color: rgb(249, 249, 249)">席タイプ</td><td style="background-color: rgb(249, 249, 249)"><%= @restaurant.seattype %></td></tr>
  <tr><td align="center" style="background-color: rgb(239, 239, 239)">決済方法</td><td style="background-color: rgb(239, 239, 239)"><%= @restaurant.pay %></td></tr>
  <tr><td align="center" style="background-color: rgb(249, 249, 249)">電話番号</td><td style="background-color: rgb(249, 249, 249)"><%= @restaurant.phone %></td></tr>
  <tr><td align="center" style="border-bottom-style:hidden;padding-bottom:0px;background-color: rgb(239, 239, 239)">ウェブサイト</td><td rowspan=2 style="background-color: rgb(239, 239, 239)"><%= @restaurant.website %></td></tr>
  <tr><td align="center" style="padding-top:0px;background-color: rgb(239, 239, 239)">SNS</td></tr>
  </table>
  </div>
  <div class="menuwhatsnew">
  <p class="detailstitle">メニュー</p>
  <%= image_tag @restaurant.menufile_url, width: 300, height: 300, 
    class: "mainimage", style: "object-fit: contain;" if @restaurant.menufile? %>
  <p class="detailstitle">最新情報</p>
  <%= @restaurant.whatsnew %>
  </div>
  </div>


<div class="comment-wrapper">
  <p class="detailstitle">コメント(<%= @comments.count %>件)</p>
  <% @comments.each do |c| %>
    <ul class="commentlistu">
      <li class="commentlisti">
        <%= image_tag c.image_url, size: "150x120" if c.image? %>
        <p><%= c.content %></p>
        <p class="commenttime"><%= c.created_at.strftime('%Y/%m/%d %H:%M') %></p>
      </li>
    </ul>
  <% end %>

  <% if user_signed_in? %>
    <p class="newcomment">新規コメント投稿</p>
    <%= form_with(model: [@restaurant, @comment], local: true) do |f| %>
      <%= f.label :content, "コメント", class: "commentlabel" %>
      <%= f.text_area :content, size: "50x5" %><br>
      <%= f.label :image, "画像添付", class: "commentlabel" %>
      <%= f.file_field :image %><br>
      <div class="commentsubmit">
      <%= button_tag type: "submit", class: "commentbutton" do %>
        <i class="far fa-comments"></i>&ensp;コメントする
      <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to "前のページに戻る", :back %>
</div>